# Generated by Django 4.1.4 on 2022-12-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villain',
            name='nemeses',
        ),
    ]
