# Generated by Django 4.1.4 on 2022-12-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_villain_nemeses'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='nemeses',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
