# Generated by Django 4.1.4 on 2022-12-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_villain_nemeses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='nemeses',
            field=models.CharField(max_length=100),
        ),
    ]
