# Generated by Django 4.1.4 on 2022-12-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_villain_nemeses'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='description',
            field=models.TextField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
