# Generated by Django 4.1.4 on 2022-12-28 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_villain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('s_window', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('N', 'Night')], default='M', max_length=1)),
                ('villain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.villain')),
            ],
        ),
    ]
