# Generated by Django 4.1.4 on 2022-12-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_s_window_surveillance_swindow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveillance',
            old_name='swindow',
            new_name='surveillance_window',
        ),
    ]
