# Generated by Django 4.1.4 on 2022-12-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_swindow_surveillance_surveillance_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveillance',
            old_name='surveillance_window',
            new_name='surv6eillance_window',
        ),
    ]
