# Generated by Django 4.1.4 on 2022-12-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_surveillance_window_surveillance_surv6eillance_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveillance',
            old_name='surv6eillance_window',
            new_name='surveillance_Window',
        ),
    ]
