# Generated by Django 4.1.4 on 2023-01-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_henchmen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Henchmen',
            new_name='Gangs',
        ),
    ]
