# Generated by Django 4.1.4 on 2023-01-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_henchmen_gangs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gangs',
            new_name='Gang',
        ),
    ]
